In [ ]:
Revision_Intensity=7
Motivation_Intensity="Lets Go! "
print(Motivation_Intensity*Revision_Intensity)

Lets Go! Lets Go! Lets Go! Lets Go! Lets Go! Lets Go! Lets Go! 


# **Always Respect your basics**

In [ ]:
first=2/3
second=2//3
third=print(2.0//3.0)
print(first)
print(second)
print(third)

0.0
0.6666666666666666
0
None


Order of Operations PEMDAS : Parentheses ,Exponents ,Multiplication/Division ,Addition/Subtraction

In [ ]:
print(min(1,2,3))
print(max(1,2,3))

1
3


In [ ]:
print(int('887')+1)

888


In [ ]:
print(int("887")+1)

888


In [ ]:
# int("Shourya") --> invalid literal for int() , not a valid representation of whole number
# int("8.0") --> invalid literal for int() , coz it is a float inside quotes

In [ ]:
a=[1,2,3]
b=[3,2,1]
a,b=b,a
print(a)
print(type(a))
print(dir(a))
# In Python , Everything can be called as Objects

[3, 2, 1]
<class 'list'>
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [ ]:
def smallest_num(a,b):
   """ This Function returns the smallest number """
   return min(a,b)
help(smallest_num)

Help on function smallest_num in module __main__:

smallest_num(a, b)
    This Function returns the smallest number



In [ ]:
def smallest_num(a,b):
   #This Function returns the smallest number
   return min(a,b)
help(smallest_num)

Help on function smallest_num in module __main__:

smallest_num(a, b)



In [ ]:
print(1,2,3,sep="<") #default-->single space

1<2<3


In [ ]:
def multiply(arg):
   return 5*arg
def square_call(fn,arg):
   return fn(arg)
def moresquare(fn,arg):
   return fn(fn(arg))
print(square_call(multiply,5),
      moresquare(multiply,5),sep="\n")

25
125


In [ ]:
def mod_5(x):
   """Return number mod 5"""
   return x%5
a=100
b=21
print("Max of numbers:",max(100,21))
print("Max of numbers mod 5:",max(100,21,key=mod_5))

Max of numbers: 100
Max of numbers mod 5: 21


In [ ]:
round(150.023,ndigits=-2)

200.0

In [ ]:
round(150.023,ndigits=2)

150.02

In [ ]:
round(151.023,ndigits=-1)

150.0

In [ ]:
round(155.023,ndigits=-1)

160.0

In [ ]:
round(-155.023,ndigits=-1)

-160.0

In [ ]:
round(-152.023,ndigits=-1)

-150.0

In [ ]:
round(-155.023,ndigits=1)

-155.0

In [ ]:
print("0"==0)
print(0.0==0)
print('0.0'==0)
print("0"=='0')
print("0"=='0.0')

False
True
False
True
False


In [ ]:
marks=[23,30,50,67]
sorted(marks)
print(marks)
print(sum(marks))

[23, 30, 50, 67]
170


In [ ]:
c=3+4j
print(c.imag) #imaginary part
c=4
print(c.bit_length())

4.0
3


In [ ]:
new_marks=[99,100]
marks.extend(new_marks)
print(marks)

[23, 30, 50, 67, 99, 100, 99, 100]


In [ ]:
marks.index(67)

3

In [ ]:
#tuples --> immutable you cannot do t[0]=100
#tuples are often used for functions that have multiple return values
x=0.125
x.as_integer_ratio()

(1, 8)

In [ ]:
squares=[x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
print("My Dog is named \"Pluto\"")
print("Pluto\'s a planet")

My Dog is named "Pluto"
Pluto's a planet


In [ ]:
test1="""Shourya
Mishra"""
test2="Shourya\nMishra"
print(test1)
print(test1==test2)

Shourya
Mishra
True


In [ ]:
Planets=['Mercury','Venus','Earth','Mars','Saturn','Jupiter','Neptune','Uranus']
Planet_initials={planet:planet[0] for planet in Planets}


In [ ]:
' '.join(sorted(Planet_initials.values()))

'E J M M N S U V'

In [ ]:
for planet,initial in Planet_initials.items():
   print(f"{planet.rjust(10)} begins with \"{initial}\"") #rjust aligns them to right after shifting 10 spaces

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
    Saturn begins with "S"
   Jupiter begins with "J"
   Neptune begins with "N"
    Uranus begins with "U"


In [ ]:
import math
print(type(math))
help(math)

<class 'module'>
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral

In [ ]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
from math import log
help(log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.

    If the base is not specified, returns the natural logarithm (base e) of x.



In [ ]:
from numpy import log
help(log)

Help on ufunc:

log = <ufunc 'log'>
    log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Natural logarithm, element-wise.

    The natural logarithm `log` is the inverse of the exponential function,
    so that `log(exp(x)) = x`. The natural logarithm is logarithm in base
    `e`.

    Parameters
    ----------
    x : array_like
        Input value.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will 

In [ ]:
import numpy
arr=numpy.random.randint(1,10,5)
print(arr)
arr.ravel()
print(arr) #now a flattened list

[4 2 9 3 1]
[4 2 9 3 1]


In [ ]:
check=[[1,2,3],[5,6,7]]
check=numpy.asarray(check)
print(check)
check=numpy.array(check)
check.ravel()

[[1 2 3]
 [5 6 7]]


array([1, 2, 3, 5, 6, 7])

In [ ]:
prog_lang="Python","Java"
print(type(prog_lang))

<class 'tuple'>


In [ ]:
game=[[0,0,1],[1,1,0],[0,1,0]]
cols=list(reversed(range(len(game))))
rows=range(len(game))
print(cols)
print(rows)

[2, 1, 0]
range(0, 3)


In [ ]:
for idx in rows:
   print(idx,cols[idx])

0 2
1 1
2 0


In [ ]:
for col,row in zip(rows,cols):
    print(col,row)

0 2
1 1
2 0


In [ ]:
for col,row in enumerate(cols):
    print(col,row)

0 2
1 1
2 0


In [ ]:
row=int(input("what row you want to play"))

what row you want to play3


### Using Pandas to get familiar with your data

The most important part of pandas library is dataframe. A Dataframe holds the type of data you might think of as a table. This is similar to sheet in excel and sql table in database

In [ ]:
# reading csv file pd.read_csv()
# data.describe() gives us the mean , std , count , min , 25% first after sorting values of each of the column of dataset.
# Y (target) can be binary , multiclass or multilabel (each row containing many ones or zeroes.For eg, an article tagged as both "politics" and "finance")
# when we have Y values in multiple columns then this is called multi column regression , otherwise single column regression.
# data.columns
# data.shape
# axis=0 means rows so data.dropna(axis=0) will drop rows having null values
# data[['price','length']] it selects multiple features

### Building models using scikit-learn

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X, y)

In [ ]:
from sklearn.metrics import mean_absolute_error

predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y, predicted_home_prices)

In [ ]:
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)
# random state 1 and 0 will be different in producing splits but they will produce same split each time we run our code and it will not create any difficulty in identifying patterns

# Define model
melbourne_model = DecisionTreeRegressor()
# Fit model
melbourne_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

### Handling Missing values

In [ ]:
# sometimes some columns of a dataset are strings but col_val.dtype prints them to be object so we can do :
# to remove them predictors.select_dtypes(exclude=['object])

In [ ]:
# get names of cols with missing values
cols_with_misssing=[col for col in X_train.columns if X_train[col].isnull().any()]

reduced_X_train=X_train.drop(cols_with_missing,axis=1)


In [ ]:
from sklearn.impute import SimpleImputer
my_imputer=SimpleTmputer()
imputed_X_train=pd.DataFrame(my_imputer.fit_transform(X_train))

# initialization changed
imp=SimpleImputer(missing_values=np.nan,strategy='most_frequent') # more given in sklearn impute documentation
imp.fit(train_data) # calculates the specific values needed for imputation
imp.transform(train_data) # performs the action actually

# number of missing values in each column of training data
missing_val_count_by_column=(train_data.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column>0])

### Handling Categorical Values

In [ ]:
# handling categrorical values --> entity embedding

In [ ]:
low_cardinality_cols=[col for col in X_train.columns if X_train[col].nunique()<10 and X_train[col].dtype=="object"]
numerical_cols=[col for col in X_train.columns if X_train[col].dtype in ['int64','float64']]

good_value_cols=low_cardinality_cols+numerical_cols

In [ ]:
# One hot encoding can handle unknown categories if they are not in training set but in validation set
# for label encoding we have to manually remove them
object_cols=[col for col in X_train.columns if X_train[col].dtype=="object"]
good_label_cols=[col for col in object_cols if set(X_Valid[col]).issubset(set(X_train[col]))]
bad_label_cols=list(set(object_cols))-set(good_label_cols)
# then drop these bad columns that should not have to be encoded
label_X_train=X_train.drop(bad_label_cols,axis=1)
label_X_valid=X_valid.drop(bad_label_cols,axis=1)



In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

label_encoder=OrdinalEncoder()

old_train_data=X_train[good_label_cols].copy()
old_valid_data=X_valid[good_label_cols].copy()

# Transform and convert to DataFrame, then reset index
old_train_data_encoded = pd.DataFrame(label_encoder.fit_transform(old_train_data), columns=old_train_data.columns)
old_valid_data_encoded = pd.DataFrame(label_encoder.transform(old_valid_data), columns=old_valid_data.columns)

# Ensure the indices are aligned with the original DataFrames before concatenation
old_train_data_encoded.index = X_train.index
old_valid_data_encoded.index = X_valid.index

# now concatenate the other columns that is not encoded

label_X_train=X_train.drop(good_label_cols,axis=1) # because their encoded values should be concatenated
label_X_valid=X_valid.drop(good_label_cols,axis=1)

label_X_train=pd.concat([label_X_train,old_train_data_encoded],axis=1)
label_X_valid=pd.concat([label_X_valid,old_valid_data_encoded],axis=1)

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# 1. Create a sample X_train with a non-default index
X_train = pd.DataFrame({
    'numerical_col': [10, 20, 30, 40, 50],
    'categorical_col_1': ['A', 'B', 'A', 'C', 'B'],
    'categorical_col_2': ['X', 'Y', 'X', 'Z', 'Y']
}, index=['row_a', 'row_b', 'row_c', 'row_d', 'row_e'])

print("Original X_train:")
print(X_train)
print("X_train index:", X_train.index.tolist())

# Define columns to be encoded
good_label_cols = ['categorical_col_1', 'categorical_col_2']

# 2. Extract and encode the categorical columns
old_train_data = X_train[good_label_cols].copy()

label_encoder = OrdinalEncoder()
encoded_array = label_encoder.fit_transform(old_train_data)

# Convert the encoded array back to a DataFrame WITHOUT setting the original index
old_train_data_encoded_wrong_index = pd.DataFrame(encoded_array, columns=good_label_cols)

print("\nEncoded DataFrame (with new default index):")
print(old_train_data_encoded_wrong_index)
print("Encoded DataFrame index:", old_train_data_encoded_wrong_index.index.tolist())

# 3. Prepare the rest of X_train by dropping the columns that were encoded
label_X_train = X_train.drop(columns=good_label_cols)
print("\nlabel_X_train (original index retained):")
print(label_X_train)
print("label_X_train index:", label_X_train.index.tolist())

# 4. Attempt to concatenate WITHOUT index alignment - THIS IS THE PROBLEM
try:
    concatenated_wrong = pd.concat([label_X_train, old_train_data_encoded_wrong_index], axis=1)
    print("\nConcatenation WITHOUT index alignment (WRONG):")
    print(concatenated_wrong)
except Exception as e:
    print(f"\nError during concatenation without index alignment: {e}")

print("\nNotice the NaNs and how rows are misaligned if the indices don't match.")

Original X_train:
       numerical_col categorical_col_1 categorical_col_2
row_a             10                 A                 X
row_b             20                 B                 Y
row_c             30                 A                 X
row_d             40                 C                 Z
row_e             50                 B                 Y
X_train index: ['row_a', 'row_b', 'row_c', 'row_d', 'row_e']

Encoded DataFrame (with new default index):
   categorical_col_1  categorical_col_2
0                0.0                0.0
1                1.0                1.0
2                0.0                0.0
3                2.0                2.0
4                1.0                1.0
Encoded DataFrame index: [0, 1, 2, 3, 4]

label_X_train (original index retained):
       numerical_col
row_a             10
row_b             20
row_c             30
row_d             40
row_e             50
label_X_train index: ['row_a', 'row_b', 'row_c', 'row_d', 'row_e']

Concatenation WIT

### The Fix: Aligning Indices

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Re-create X_train for demonstration
X_train = pd.DataFrame({
    'numerical_col': [10, 20, 30, 40, 50],
    'categorical_col_1': ['A', 'B', 'A', 'C', 'B'],
    'categorical_col_2': ['X', 'Y', 'X', 'Z', 'Y']
}, index=['row_a', 'row_b', 'row_c', 'row_d', 'row_e'])

good_label_cols = ['categorical_col_1', 'categorical_col_2']

old_train_data = X_train[good_label_cols].copy()
label_encoder = OrdinalEncoder()
encoded_array = label_encoder.fit_transform(old_train_data)

# Convert the encoded array back to a DataFrame AND set the original index
old_train_data_encoded_correct_index = pd.DataFrame(encoded_array, columns=good_label_cols)
old_train_data_encoded_correct_index.index = X_train.index # <<< THIS IS THE CRUCIAL STEP

print("Encoded DataFrame (with CORRECT original index):")
print(old_train_data_encoded_correct_index)
print("Encoded DataFrame index:", old_train_data_encoded_correct_index.index.tolist())

# Prepare the rest of X_train
label_X_train = X_train.drop(columns=good_label_cols)

# Concatenate WITH index alignment (CORRECT)
concatenated_correct = pd.concat([label_X_train, old_train_data_encoded_correct_index], axis=1)

print("\nConcatenation WITH index alignment (CORRECT):")
print(concatenated_correct)

print("\nAs you can see, explicitly setting the index ensures that concatenation aligns the rows correctly, preventing data corruption or NaNs.")

Encoded DataFrame (with CORRECT original index):
       categorical_col_1  categorical_col_2
row_a                0.0                0.0
row_b                1.0                1.0
row_c                0.0                0.0
row_d                2.0                2.0
row_e                1.0                1.0
Encoded DataFrame index: ['row_a', 'row_b', 'row_c', 'row_d', 'row_e']

Concatenation WITH index alignment (CORRECT):
       numerical_col  categorical_col_1  categorical_col_2
row_a             10                0.0                0.0
row_b             20                1.0                1.0
row_c             30                0.0                0.0
row_d             40                2.0                2.0
row_e             50                1.0                1.0

As you can see, explicitly setting the index ensures that concatenation aligns the rows correctly, preventing data corruption or NaNs.


### Pipelines
Pipelines are a simple way to keep your data preprocessing and modelling code organized. Specifically , a pipeline bundles preprocessing and modelling steps
so you can use the whole bundle as if it were a single step.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numerical_transformer=SimpleImputer(strategy='constant')

categorical_transformer=Pipeline(steps[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])
preprocessor=ColumnTransformer(
    transformers=[
        ('num',numerical_transformer,numerical_cols),
        ('cat',categorical_transformer,categorical_cols)
    ]
)
my_pipeline=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('model',model)
])

In [ ]:
# Stratified K folding ensures that in each of the folds we have the same number of positive and negative samples
from sklearn.model_selection import StratifiedKFold
StratifiedKFold(n_splits=5,shuffle=True,random_state=1)

# Holdout validation when we have millions of rows in a dataset
# you can also divide your data using bins using pd.cut

### Data Leakage :
when your training data contains information about the target, but similar data will not be available when the model is used for prediction .

### Target Leakage :
It occurs when when your predictors include data that will not be available at the time you make predictions.When some features try to become another value then predictions start differing singnificantly .

### Train Test Contamination
When we are not careful about how to distinguish between training and validation data
Recall that validation is meant to be a measure of how the model does on that data that it has not considered before. You can corrupt the behaviour if the validation data affects the preprocessing behaviour.

So just remove that features that could be suspected to provide not much information during predictions rather can confuse it .
For wg , prices can go up and down drastically affecting the performance of the predictions . We can get same predictions for two different value of features .

In [ ]:
# Applying cross validation
kf=model_selection.KFold(n_splits=5,shuffle=True,random_state=1)
for fold,(train_indices,valid_indices) in enumerate(kf.split(X=df_train)):
   df_train.loc[valid_indices,'kfold']=fold

### Feature Engineering Approaches

1) with numerical features , we can standardize them , we subtract mean value by the feature divided by standard deviation


scaler=preprocessing.StandardScaler()
xtrain[numerical_cols]=scaler.fit_transform(xtrain[numerical_cols])

2) we can normalize the numerical columns

3) we can do log transformation

for col in numerical_cols:
    df[col]=np.log1p(df[col])

4) sklearn.preprocessing.PolynomialFeatures(degree=2,*,interaction_only=False,include_bias=True,order='C)
it generate polynomial and interaction features . Generate a new feature matrix consisting of all polynomial combinations of the features with degree less than or equal to the specified degree.
if an input sample is two dimensional and of the form [a,b] , the degree-2 polynomial features are of the form [1,a,b,a^2,a*b,b^2]

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X=np.arange(6).reshape(3,2)
print(X)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
poly=PolynomialFeatures(2)
X_transformed = poly.fit_transform(X)
print(X_transformed)
# first val is the bias term and then a , b , a^2 , a*b , b^2

[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [ ]:
# interaction only features will give only a*b
poly=PolynomialFeatures(interaction_only=True)
X_transformed=poly.fit_transform(X)
print(X_transformed) # only contains multiplication term

[[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]


5) Binning the numerical features using pd.cut

6) one hot encoding of categorical variables + standardization of ohe and numerical

### Target Encoding with K-Fold Cross-Validation

Target encoding replaces a categorical feature with the mean of the target variable for that category. It's crucial to perform this carefully within a cross-validation setup to avoid **data leakage**. If you calculate the mean target across the entire dataset and then use it on both training and validation sets, your model will gain information about the validation target, leading to overly optimistic performance estimates.

Here's the general process:
1.  **Create a sample DataFrame** with a categorical feature and a numerical target.
2.  **Define K-Folds:** Split your data into `k` folds.
3.  **Iterate through Folds:** For each fold:
    *   Use the *training portion* of the fold to calculate the mean target value for each category of your chosen feature.
    *   Apply these calculated means to encode the categorical feature in the *validation portion* of the fold.
    *   To handle categories present in the validation set but not in the training set (or for regularization), a smoothing factor or a global mean can be used. For simplicity, we'll use the global mean for unseen categories in this example.

Let's start by creating a sample dataset.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

# Create a sample DataFrame
data = {
    'categorical_feature': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'D'],
    'target': [10, 20, 12, 30, 22, 11, 28, 25, 15, 40]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\nGlobal Mean Target:", df['target'].mean())


Original DataFrame:
  categorical_feature  target
0                   A      10
1                   B      20
2                   A      12
3                   C      30
4                   B      22
5                   A      11
6                   C      28
7                   B      25
8                   A      15
9                   D      40

Global Mean Target: 21.3


Now, let's implement the target encoding with K-Fold cross-validation. We will add a new column `target_encoded_feature` to our DataFrame. This column will be populated differently for each fold based on the training data of that fold.

In [ ]:
feature_to_encode = 'categorical_feature'
target_column = 'target'
n_splits = 5
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
df['target_encoded_value'] = np.nan

for fold, (train_index, val_index) in enumerate(kf.split(df)):

    train_df = df.iloc[train_index]
    val_df = df.iloc[val_index]

    target_means = train_df.groupby(feature_to_encode)[target_column].mean()
    print(f"Target Means (from training fold {fold + 1}):\n{target_means}")
    global_mean = train_df[target_column].mean()
    print(f"Global Mean (from training fold {fold + 1}): {global_mean:.2f}")

    # Map the target means to the validation set
    # Use fillna(global_mean) to handle categories present in val_df but not in train_df
    encoded_values = val_df[feature_to_encode].map(target_means).fillna(global_mean)

    # Assign the encoded values back to the original DataFrame at the correct indices
    df.loc[val_index, 'target_encoded_value'] = encoded_values


print("\nDataFrame with Target Encoded Feature:")
print(df)

# Verify that each original categorical value maps to an average of its target_encoded_value
# Note: Due to KFold, a single category might have slightly different encoded values
# depending on which fold it was in the validation set. This is expected and desirable.
print("\nAverage Target Encoded Value for each original category (across all folds):")
print(df.groupby(feature_to_encode)['target_encoded_value'].mean())


Target Means (from training fold 1):
categorical_feature
A    11.0
B    23.5
C    29.0
D    40.0
Name: target, dtype: float64
Global Mean (from training fold 1): 22.25
Target Means (from training fold 2):
categorical_feature
A    13.500000
B    22.333333
C    29.000000
D    40.000000
Name: target, dtype: float64
Global Mean (from training fold 2): 24.00
Target Means (from training fold 3):
categorical_feature
A    12.0
B    21.0
C    29.0
D    40.0
Name: target, dtype: float64
Global Mean (from training fold 3): 22.00
Target Means (from training fold 4):
categorical_feature
A    12.0
B    22.5
C    29.0
Name: target, dtype: float64
Global Mean (from training fold 4): 18.88
Target Means (from training fold 5):
categorical_feature
A    12.000000
B    22.333333
D    40.000000
Name: target, dtype: float64
Global Mean (from training fold 5): 19.38

DataFrame with Target Encoded Feature:
  categorical_feature  target  target_encoded_value
0                   A      10                13.500
1

### Explanation:

*   **Data Leakage Prevention:** By calculating target_means *only* from the train_df for each fold and applying it to the val_df, we ensure that the validation set's target values do not influence the encoding. This provides a more realistic estimate of your model's performance on unseen data.
*   **fillna(global_mean):** If a category appears in a val_df but was not present in the corresponding train_df, its target_encoded_value would be NaN after mapping. We fill these NaN s with the global_mean of the target from the train_df to provide a reasonable default. More sophisticated methods might involve adding a small amount of random noise or using a smoothed average.
*   **Final df['target_encoded_value']:** After the loop, the target_encoded_value column in the original df will contain the encoded values, with each row's encoding derived from the training folds where that row was part of the validation set. This column can now be used as a numerical feature in your model training.

Let's deep dive into target encoding with K-Fold cross-validation. The key concept here is **data leakage**, and how we prevent it to get a reliable measure of our model's performance. Think of it like this:

Imagine you're trying to predict if a student will pass an exam. If you accidentally peek at the exam answers *before* you train your prediction model, your model will look incredibly accurate on that exam, but it will fail miserably on any *new* exam.

In machine learning, **data leakage** means your training data contains information about the target variable that wouldn't normally be available at prediction time. For target encoding, if you calculate the average target value for each category using the *entire* dataset and then use those averages to encode your features, your model will have 'peeked' at the target values for the validation set. This makes your model seem better than it truly is.

Here's how **K-Fold Cross-Validation for Target Encoding** solves this, step-by-step:

1.  **Divide Your Data (K-Folds)**: First, we split your entire dataset (like our `df` with `categorical_feature` and `target`) into several chunks, let's say 5 folds. Each fold will take a turn being the 'validation set', while the other 4 folds become the 'training set'.

    *   **Example**: If your data has 10 rows, Fold 1 might be rows 0,1. Fold 2 might be rows 2,3, and so on.

2.  **Iterate Through Each Fold (The 'Exam' Analogy)**:

    *   **Step A: Training the 'Teacher' (on `train_df`)**: For each iteration, we take the `train_df` (e.g., 80% of your data). We then calculate the *average target value* for each unique category (`A`, `B`, `C`, `D`) *only within this `train_df`*. This is like the teacher learning about the students' abilities based on their homework (training data).

        *   **Crucial Point**: The `val_df` for this specific fold is completely *hidden* at this stage.

    *   **Step B: Applying to the 'Student' (on `val_df`)**: Now, we take these averages we just calculated from the `train_df` and use them to encode the `categorical_feature` in the `val_df` (the remaining 20% of the data for this iteration). Each category in the `val_df` gets replaced by its corresponding average target value *learned from the `train_df`*.

        *   **Analogy**: The teacher then grades the student on the exam (validation data) based *only* on what they learned from the homework, not based on the exam answers.

    *   **Step C: Handling Unseen Categories (`fillna(global_mean)`)**: What if a category appears in your `val_df` that was *not* present in the `train_df` for that specific fold? If we tried to map an average, it wouldn't find one. To handle this, we fill it with a sensible default, usually the overall average target value from the `train_df` (`global_mean`). This is a fallback measure.

    *   **Step D: Store the Result**: We store these newly encoded values for the `val_df` back into our main DataFrame at the correct positions.

3.  **Repeat for All Folds**: This entire process (Steps A, B, C, D) is repeated for each of the 5 folds. This ensures that every single row in your original DataFrame gets an `target_encoded_value` that was generated without any knowledge of that row's *own* target value.

**What `df['target_encoded_value']` Represents:**

After the loop finishes, the `target_encoded_value` column in your `df` will contain a numerical representation for each categorical entry. Each entry's value was determined by averaging the target of *other* rows belonging to the same category, strictly separated by the cross-validation folds. This results in a much more honest and leak-free feature that your model can learn from.

This method is particularly effective for high-cardinality categorical features (features with many unique categories), where one-hot encoding might create too many columns and lead to sparsity.

### When each fold was part of the validation set for that specific iteration then its target encoded feature column is generated and eventually gets their target encoded feature columns filled which replaced the c

### Hyperparameter tuning using optuna

### Model Blending and Stacking : https://www.kaggle.com/code/abhishek/competition-part-5-blending-101